/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.entities.Train;
import org.example.entities.User;
import org.example.service.UserBookingService;
import org.example.util.UserServiceUtil;

import java.io.IOException;
import java.util.*;

public class App {
    public String getGreeting() {
        return "Hello";
    }

    public static void main(String[] args) {
        System.out.println("Train Booking System");
        Scanner sc = new Scanner(System.in);
        int choice=0;
        UserBookingService userBookingService;
        try {
            userBookingService = new UserBookingService();
        }
        catch (IOException e){
            System.out.println("Something went wrong.");
            return;
        }

        while (choice!=7){
            System.out.println("Make Choice:");
            System.out.println("1:SignUp");
            System.out.println("2:Login");
            System.out.println("3:Search Trains");
            System.out.println("4:Book Seat");
            System.out.println("5:Fetch Bookings");
            System.out.println("6:Cancel Tickets");
            System.out.println("7:Exit App");
            choice= sc.nextInt();
            Train selectedTrain = new Train();
            switch (choice){
                case 1:
                    System.out.println("Enter UserName to SignUp:");
                    String signUpName = sc.nextLine();
                    System.out.println("Enter password:");
                    String password = sc.nextLine();
                    User userToSignUp = new User(signUpName, password, UserServiceUtil.hashedPassword(password), new ArrayList<>(), UUID.randomUUID().toString());
                    userBookingService.signUpUser(userToSignUp);
                    break;
                case 2:
                    System.out.println("Enter UserName to SignUp:");
                    String loginName = sc.nextLine();
                    System.out.println("Enter password:");
                    String loginPassword = sc.nextLine();
                    User userToLogin = new User(loginName, loginPassword, UserServiceUtil.hashedPassword(loginPassword), new ArrayList<>(), UUID.randomUUID().toString());
                    try {
                        userBookingService = new UserBookingService(userToLogin);
                    }
                    catch (IOException e){
                        return;
                    }
                    break;
                case 3:
                    System.out.println("Enter your source:");
                    String source = sc.nextLine();
                    System.out.println("Enter your destination:");
                    String destination = sc.nextLine();
                    List<Train> trains = userBookingService.getTrains(source, destination);
                    int index=1;
                    for (Train t : trains){
                        System.out.println(index + " Train ID " + t.getTrainID());
                        for (Map.Entry<String, String> entry : t.getStationArrivalTime().entrySet()){
                            System.out.println("Station : " + entry.getKey() + "Time : " + entry.getValue());
                        }
                    }
                    System.out.println("Type number to select train : ");
                    selectedTrain = trains.get(sc.nextInt());
                    break;
                case 4:
                    System.out.println("Enter choice of seat out of available seats:");
                    List<List<Integer>> seats = userBookingService.fetchSeats(selectedTrain);
                    for (List<Integer> row : seats){
                        for (int val : row){
                            System.out.println(val + " ");
                        }
                        System.out.println();
                    }
                    System.out.println("Select desired row:");
                    int row = sc.nextInt();
                    System.out.println("Select desired column:");
                    int cols = sc.nextInt();
                    System.out.println("Processing...");
                    boolean booked = userBookingService.bookSeat(selectedTrain, row, cols);
                    if(booked){
                        System.out.println("Booking Successful.");
                    }
                    else System.out.println("Booking Failed.");
                    break;
                case 5:
                    System.out.println("Fetch ticket booking information.");
                    userBookingService.fetchBooking();
                    break;
                case 6:
                    System.out.println("Enter ticket ID for cancellation :");
                    String tktID = sc.nextLine();
                    userBookingService.cancelBooking(tktID);
                    break;
                case 7:
                    System.out.println("Exiting User.");
                    break;
                default:
                    System.out.println("Wrong Choice. Choose between 1-7.");
            }

        }
    }
}
